### ISSUE TITLE
Lack of context in log messages

### ISSUE THREAD

**Issue by necrophonic** [ONSdigital/ras-secure-message#133]
There seem to be a lot of log messages that are missing any kind of context, e.g:

https://github.com/ONSdigital/ras-secure-message/blob/2dc5b294875192fe79a1bcf82fdb2ed30cf2f423/secure_message/resources/messages.py#L54

There's no reference that can be tied back to any particular message and no way of tying this message to a subsequent error further down in the same method.

Logging without context (transaction id / collaboration id etc) is not useful for debugging and just emits noise into the logs.

**Comment by insacuri** [comment]
Closing as we've improved this over the years.  It might not be perfect but it's better than it was in a lot of places.
